flowchart TB
    KEY(["識別名 canonical key = nextcloud"])
    KEY --> SN["osf.io アドオン<br/>short_name = nextcloud"]
    KEY --> PV["osf.io アドオン<br/>_provider = nextcloud"]
    KEY --> WK["GravyValet<br/>wb_key = nextcloud"]
    KEY --> AI["GravyValet<br/>addon_imp_name = NEXTCLOUD<br/>.lower() = nextcloud"]
    KEY --> EP["WaterButler<br/>エントリポイント名 = nextcloud"]
    KEY --> LB["osf.io アドオン<br/>label / app_label = addons_nextcloud"]
